export const FETCH_COMPANIES_SUCCESS = 'FETCH_COMPANIES_SUCCESS';
export const FETCH_COMPANIES_FAIL = 'FETCH_COMPANIES_FAIL';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const FETCH_USER_START = 'fETCH_USER_START';
export const FETCH_USER_SUCCESS = 'fETCH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'fETCH_USER_FAIL';

export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';

export const LOGOUT_SUCCESS = 'LOGLOGOUT_SUCCESSOUT';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const FETCH_TOPICS_START = 'FETCH_TOPICS_START';
export const FETCH_TOPICS_SUCCESS = 'FETCH_TOPICS_SUCCESS';
export const FETCH_TOPICS_FAIL = 'FETCH_TOPICS_FAIL';

export const ADD_TOPIC_START = 'ADD_TOPIC_START';
export const ADD_TOPIC_SUCCESS = 'ADD_TOPIC_SUCCESS';
export const ADD_TOPIC_FAIL = 'ADD_TOPIC_FAIL';

export const VOTE_TOPIC_START = 'VOTE_TOPIC_START';
export const VOTE_TOPIC_SUCCESS = 'VOTE_TOPIC_SUCCESS';
export const VOTE_TOPIC_FAIL = 'VOTE_TOPIC_FAIL';

export const DELETE_TOPIC_START = 'DELETE_TOPIC_START';
export const DELETE_TOPIC_SUCCESS = 'DELETE_TOPIC_SUCCESS';
export const DELETE_TOPIC_FAIL = 'DELETE_TOPIC_FAIL';


export const FETCH_TEAMS_START = 'FETCH_TEAMS_START';
export const FETCH_TEAMS_SUCCESS = 'FETCH_TEAMS_SUCCESS';
export const FETCH_TEAMS_FAIL = 'FETCH_TEAMS_FAIL';

export const FETCH_PROJECTS_START = 'FETCH_PROJECTS_START';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';
export const FETCH_PROJECTS_FAIL = 'FETCH_PROJECTS_FAIL';

export const VOTE_PROJECT_START = 'VOTE_PROJECT_START';
export const VOTE_PROJECT_SUCCESS = 'VOTE_PROJECT_SUCCESS';
export const VOTE_PROJECT_FAIL = 'VOTE_PROJECT_FAIL';